console.time('your code took');
console.log('hello console');
console.log(4+34);
console.log(34);
console.log(true);
console.log([34 , 2 , 1 , 2]);
console.log({harry: "this" , marks: 34});
console.table({harry: "this" , marks: 34});
console.warn('this is a warning');
//console.clear();
console.timeEnd('your code took');
console.error('this is an error');
console.clear();
console.assert(578>190 , 'this is not possible');